CREATE TABLE `lottery_let_detail` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `turn` char(10) NOT NULL,
  `pdate` datetime NOT NULL,
  `code_1` char(4) NOT NULL,
  `code_2` char(4) NOT NULL,
  `code_3` char(4) NOT NULL,
  `code_4` char(4) NOT NULL,
  `code_5` char(4) NOT NULL,
  `code_6` char(4) NOT NULL,
  `code_7` char(4) NOT NULL,
  `c_total` char(30) NOT NULL COMMENT '当期总额',
  `total` char(30) NOT NULL COMMENT '滚动总额',
  `p_1` char(20) NOT NULL,
  `p_2` char(20) NOT NULL,
  `p_3` char(20) NOT NULL,
  `p_4` char(20) NOT NULL,
  `p_5` char(20) NOT NULL,
  `p_6` char(20) NOT NULL,
  `p_1_num` char(20) NOT NULL,
  `p_2_num` char(20) NOT NULL,
  `p_3_num` char(20) NOT NULL,
  `p_4_num` char(20) NOT NULL,
  `p_5_num` char(20) NOT NULL,
  `p_6_num` char(20) NOT NULL,
  `pl_1` char(20) NOT NULL COMMENT '加奖 1 金额',
  `pl_2` char(20) NOT NULL,
  `pl_3` char(20) NOT NULL,
  `pl_1_num` char(20) NOT NULL COMMENT '加奖 1 数量',
  `pl_2_num` char(20) NOT NULL,
  `pl_3_num` char(20) NOT NULL,
  `ballturn` char(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=191 DEFAULT CHARSET=utf8;